# Template compose file for sharded tests - uses pre-built image and shared PostgreSQL
services:
  matchzy-tournament:
    image: matchzy-test:sharded
    container_name: SHARD_APP_NAME
    restart: unless-stopped
    ports:
      - 'SHARD_PORT:3069'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_TOKEN=${API_TOKEN:-admin123}
      - SERVER_TOKEN=${SERVER_TOKEN:-server123}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@SHARED_POSTGRES_HOST:SHARED_POSTGRES_PORT/SHARD_DB_NAME
      - DB_HOST=SHARED_POSTGRES_HOST
      - DB_PORT=SHARED_POSTGRES_PORT
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=SHARD_DB_NAME
      - VITE_ENABLE_DEV_PAGE=true
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3069/health']
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - matchzy-test-network

networks:
  matchzy-test-network:
    external: true
    name: matchzy-test-network

volumes:
  matchzy-data:
    driver: local

